### ISSUE TITLE
Jail Free Card

### ISSUE THREAD

**Issue by ghost** [akhilmanhattan/big_projects#3]
https://github.com/akhilmanhattan/big_projects/blob/c2a803d1360b095c188511b84c335b3a8b68ddea/Monopoly/monopoly_basic/game.py#L351

What is the point of this line if the get out of jail free card does nothing?

**Comment by ghost** [comment]
https://github.com/akhilmanhattan/big_projects/blob/204bddfff87309e7163aa4aedf3e402911be1dc0/Monopoly/monopoly_basic/main.py#L237

I see. You are just keeping consistency with the arguments. Sorry for the concern. I can see that the point of that is in the main.py, not the game.py. Forgive me for being to quick to post.

**Comment by akhilb1644** [comment]
It's alright, I can sometimes just be like that too: assuming before I see the whole picture.
